services:
  postgres:
    image: 'postgres:16-alpine' # Alpine is much smaller/lighter
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data so it survives restarts

volumes:
  postgres-data: # Define the volume name hereservices: {}
